### ISSUE TITLE
Cluster fails to start

### ISSUE THREAD

**Issue by adrpino** [graphaware/neo4j-casual-cluster-quickstart#1] opened 2018-01-22 16:40 UTC
Running `docker-compose up` gives the following error:

```
core3_1  | 2018-01-22 16:37:30.423+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4c36250e' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4c36250e' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}".
core3_1  | org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4c36250e' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}".
core3_1  |      at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
core3_1  |      at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
core3_1  |      at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
core3_1  |      at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
core3_1  |      at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
core3_1  | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4c36250e' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}".
core3_1  |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
core3_1  |      at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
core3_1  |      at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
core3_1  |      ... 3 more
core3_1  | Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
core3_1  |      at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
core3_1  |      at org.neo4j.causalclustering.core.CommercialCoreGraphDatabase.<init>(CommercialCoreGraphDatabase.java:33)
core3_1  |      at org.neo4j.causalclustering.core.CommercialCoreGraphDatabase.<init>(CommercialCoreGraphDatabase.java:24)
core3_1  |      at org.neo4j.server.enterprise.CommercialNeoServer.lambda$static$0(CommercialNeoServer.java:28)
core3_1  |      at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
core3_1  |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
core3_1  |      ... 5 more
core3_1  | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.causalclustering.core.state.CoreLife@4a8ab068' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}".
core3_1  |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
core3_1  |      at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
core3_1  |      at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
core3_1  |      ... 10 more
core3_1  | Caused by: org.neo4j.causalclustering.identity.BindingException: Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}
core3_1  |      at org.neo4j.causalclustering.identity.ClusterBinder.publishClusterId(ClusterBinder.java:129)
core3_1  |      at org.neo4j.causalclustering.identity.ClusterBinder.bindToCluster(ClusterBinder.java:76)
core3_1  |      at org.neo4j.causalclustering.core.state.CoreLife.start(CoreLife.java:72)
core3_1  |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
core3_1  |      ... 12 more
core3_1  |      Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Exception during graceful attempt to stop partially started component. Please use non suppressed exception to see original component failure.
core3_1  |              at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:457)
core3_1  |              ... 12 more
core3_1  |      Caused by: java.lang.NullPointerException
core3_1  |              at org.neo4j.causalclustering.core.replication.session.GlobalSessionTrackerState.access$100(GlobalSessionTrackerState.java:38)
core3_1  |              at org.neo4j.causalclustering.core.replication.session.GlobalSessionTrackerState$Marshal.marshal(GlobalSessionTrackerState.java:152)
core3_1  |              at org.neo4j.causalclustering.core.replication.session.GlobalSessionTrackerState$Marshal.marshal(GlobalSessionTrackerState.java:139)
core3_1  |              at org.neo4j.causalclustering.core.state.storage.DurableStateStorage.persistStoreData(DurableStateStorage.java:128)
core3_1  |              at org.neo4j.causalclustering.SessionTracker.flush(SessionTracker.java:54)
core3_1  |              at org.neo4j.causalclustering.core.state.CoreState.flush(CoreState.java:61)
core3_1  |              at org.neo4j.causalclustering.core.state.CommandApplicationProcess.stop(CommandApplicationProcess.java:297)
core3_1  |              at org.neo4j.causalclustering.core.state.CoreLife.stop(CoreLife.java:99)
core3_1  |              at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:453)
core3_1  |              ... 12 more
core3_1  | 2018-01-22 16:37:30.428+0000 INFO  Neo4j Server shutdown initiated by request
```

Am I doing something wrong?

**Comment by espiegelberg** [comment] 2018-01-22 18:25
The above stacktrace includes:

Caused by: org.neo4j.causalclustering.identity.BindingException: Failed to publish: ClusterId{uuid=6d3642cd-b755-4914-8f93-41eeedfc1906}

Which indicates that something is already listening on the ports required by the cluster. Do you have something else -- a standalone instance of Neo4j perhaps -- already running on your machine? 

Please ensure that all ports listed in the docker-compose.yml are free (or change them to different values) and start the cluster.

**Comment by adrpino** [comment] 2018-01-22 18:51
I discovered that it work if I comment out the `volumes` section in each member, could this be the issue?

**Comment by espiegelberg** [comment] 2018-01-23 14:17
To be honest, commenting out the volumes section in each member does not fit with my understanding (from having seen a BindingException in your logs), but it sounds that it has solved your issue nevertheless and you are now able to successfully start your cluster.

Is your cluster now up and running? If yes, (great!) please close this issue.

**Closed as completed** 2018-01-23 14:53 UTC
